spring:
  datasource:
    url: jdbc:mysql://localhost:3306/make_portfolio?serverTimezone=JST
    username: root
    password: sqlMyTe310nowing
    driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: yshantian833@gmail.com
    password: jbrpquobwxjuisbi
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
